# Site settings
title: Mário Ferreira
description: Website of Mário Ferreira
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: marioviana.github.io #"localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mário Ferreira
user_description: Just cool.
user_title: Under construction
email: mariovianaferreira@gmail.com
linkedin_username: marioviana
github_username:  marioviana
facebook_username:  mariojvf

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
